volumes:
  build-user-app:
  build-admin-panel:
  pg-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./pg-data
  pgadmin-data:
  debug:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./debug

services:
  postgres:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dahakalab
    env_file:
      - .env.sds
    volumes:
      - pg-data:/var/lib/postgresql/data

  cosmetology-server:
    image: dahakalab/cosmetology-backend:latest
    container_name: cosmetology-server
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: dahakalab
      DB_NAME: cosmetology
    env_file:
      - .env.sds
    depends_on:
      - postgres

  cosmetology-user-app:
    depends_on:
      - cosmetology-server
    image: dahakalab/cosmetology-user-app:latest
    container_name: cosmetology-user-app
    env_file:
      - .env.front
    volumes:
      - build-user-app:/app/build

  cosmetology-admin-panel:
    depends_on:
      - cosmetology-server
    image: dahakalab/cosmetology-admin-panel:latest
    container_name: cosmetology-admin-panel
    env_file:
      - .env.front
    volumes:
      - build-admin-panel:/app/build

  app-web-server:
    depends_on:
      - cosmetology-user-app
    image: nginx:alpine
    container_name: app-web-server
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - build-user-app:/usr/share/nginx/html:ro
      - debug:/var/log/nginx

  admin-web-server:
    depends_on:
      - cosmetology-admin-panel
    image: nginx:alpine
    restart: always
    container_name: admin-web-server
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/admin.conf:/etc/nginx/conf.d/default.conf:ro
      - build-admin-panel:/usr/share/nginx/html:ro
      - debug:/var/log/nginx
